# Generated by Django 3.0.3 on 2020-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impurity_name', models.CharField(max_length=1024)),
                ('cas_no', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField()),
                ('current_price', models.PositiveIntegerField()),
                ('actual_price', models.PositiveIntegerField()),
                ('image_file', models.ImageField(upload_to='impurities')),
            ],
        ),
    ]
