# Generated by Django 3.0.3 on 2020-05-23 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cateogry', models.CharField(max_length=256)),
                ('expiry_date', models.DateField()),
                ('purity', models.IntegerField()),
                ('place', models.CharField(max_length=512)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_details', to='my_site.Post')),
            ],
        ),
    ]
