# Generated by Django 3.0.3 on 2020-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_postdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='purity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
