# Generated by Django 3.0.3 on 2020-05-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20200523_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='impurity_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
