# Generated by Django 3.0.3 on 2020-05-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_auto_20200523_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetails',
            name='state',
            field=models.CharField(default='solid', max_length=333),
            preserve_default=False,
        ),
    ]
