# Generated by Django 3.0.3 on 2020-05-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_auto_20200523_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetails',
            old_name='solubility',
            new_name='sub_cateogry',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='mol_fm',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='mol_wt',
        ),
    ]
