# Generated by Django 3.0.3 on 2020-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0007_auto_20200523_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetails',
            old_name='sub_cateogry',
            new_name='solubility',
        ),
        migrations.AddField(
            model_name='postdetails',
            name='mol_fm',
            field=models.CharField(blank=True, max_length=111),
        ),
        migrations.AddField(
            model_name='postdetails',
            name='mol_wt',
            field=models.CharField(blank=True, max_length=333),
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='state',
            field=models.CharField(blank=True, max_length=333),
        ),
    ]
