# Generated by Django 3.0.3 on 2020-05-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_auto_20200523_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
