# Generated by Django 3.0.3 on 2020-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0009_auto_20200523_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetails',
            name='chemical_name',
            field=models.CharField(default='1', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
