# Generated by Django 3.0.3 on 2020-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0010_auto_20200523_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetails',
            name='chemical_name',
        ),
        migrations.AddField(
            model_name='post',
            name='chemical_name',
            field=models.CharField(default='s', max_length=512),
            preserve_default=False,
        ),
    ]
