# Generated by Django 3.0.3 on 2020-05-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0011_auto_20200523_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('mobile', models.PositiveIntegerField(help_text='By Default extension number is (+91).\nPlease enter the pin-code in case of telephone')),
                ('email', models.EmailField(help_text='We dont spam you..!!', max_length=256)),
                ('place', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True, max_length=11111)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='my_site.Post')),
            ],
        ),
    ]
