# Generated by Django 3.0.3 on 2020-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(help_text='By Default extension number is (+91).\nPlease enter the pin-code in case of telephone', max_length=521),
        ),
    ]
