# Generated by Django 3.0.3 on 2020-05-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0013_auto_20200523_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default='2019-05-22 21:03'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(help_text='Default extension (+91).\nPlease enter the pin-code in case of telephone', max_length=521),
        ),
    ]
