# Generated by Django 3.0.3 on 2020-05-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0015_auto_20200524_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
