# Generated by Django 3.0.3 on 2020-05-24 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0016_auto_20200524_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 24, 14, 45, 25, 372712)),
        ),
    ]
