# Generated by Django 3.0.3 on 2020-05-24 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0017_auto_20200524_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 24, 9, 18, 15, 257136, tzinfo=utc)),
        ),
    ]
