# Generated by Django 3.0.3 on 2020-05-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='post',
        ),
    ]
