# Generated by Django 3.0.3 on 2020-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_post_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
